<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3f882a3b-1f1c-41e7-8163-2adc5572e81b</UserSecretsId>
    <ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CloudinaryDotNet" Version="1.29.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.26" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="OpenApiUi" Version="1.1.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\HandoraInfrastructure\HandoraInfrastructure.csproj" />
    <ProjectReference Include="..\HandoraApplication\HandoraApplication.csproj" />
    <ProjectReference Include="..\HandoraMVC\HandoraMVC.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <Target Name="CopyVCConfig" AfterTargets="Publish">
    <ItemGroup>
      <VCDlls Include="C:\Windows\System32\vcruntime140.dll;C:\Windows\System32\msvcp140.dll;C:\Windows\System32\vcruntime140_1.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(VCDlls)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>